server:
  port: 3000
  servlet.context-path: /
  shutdown: graceful
  

spring:
  threads.virtual.enabled: true
  jackson.deserialization.ACCEPT_FLOAT_AS_INT: false
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:5432/rinha?loggerLevel=OFF
    username: admin
    password: 123
    hikari:
      pool-name: rinha-backend
      initializationFailTimeout: 40000 
